spring.application.name=SecureLoginAPI

spring.datasource.url=jdbc:mysql://localhost:3306/securitydb
spring.datasource.username=root
spring.datasource.password=Sams@2511

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080